debug: false
management.endpoints.web.exposure.include: "*"
server.servlet.session.timeout: 54000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/snsdb
    driver-class-name: org.postgresql.Driver
    username: snsuser
    password: 1234567
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
  h2.console.enabled: true
  sql.init.mode: always
logging:
  level:
    com.example.sns: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
jwt:
  secret-key: fast-campus.sns_secret_key-for-tokenization
  token:
    expired-time-ms: 2592000000

springdoc:
  packages-to-scan: com.example.sns.controller
  swagger-ui:
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true